### ISSUE TITLE
ubuntu 16.04 PHP7 "fatal error: main/php.h: No such file or directory"

### ISSUE THREAD

**Issue by alash3al** [deuill/go-php#35]
sorry, this may be a wrong place ?
i've ubuntu 16.04, the php include path is located at `/usr/include/php/20151012`,
is there any trick that will solve that issue using any ENV var ?

**Comment by deuill** [comment]
Hi @alash3al, can you try building with the `php7.debian` tag, i.e.:

```
go build -tags php7.debian
```

You'll need to pass that tag for any package that depends on `go-php` as well.

**Comment by alash3al** [comment]
Thanks @deuill , i tried that, and it worked as expected,
sorry because i didn't discovered that solution myself .

**Comment by deuill** [comment]
No problem, glad it worked! I should probably add a section for this in the README. Closing, please open a new issue if you have any further problems/questions!
