### ISSUE TITLE
Get or set value to the php script in go .

### ISSUE THREAD

**Issue by xulei8** [deuill/go-php#6]
We need put or get values to php script in golang .

**Comment by deuill** [comment]
You can bind Go variables (except for functions and method receivers) into PHP using the [`Context.Bind`](https://godoc.org/github.com/deuill/go-php/context#Context.Bind) method. Transformation rules are covered in the [`value.New`](https://godoc.org/github.com/deuill/go-php/value#New) preamble.

You can return PHP variables for use in the Go context using [`Context.Eval`](https://godoc.org/github.com/deuill/go-php/context#Context.Eval), which returns a non-nil `*Value` type if the eval'd string returns anything.

**Comment by deuill** [comment]
As an aside, the included tests are usually a good example of how the code is supposed to be used. For example, binding Go variables to PHP contexts [here](https://github.com/deuill/go-php/blob/e031953f3b8a853bde980259780c738f89359127/php_test.go#L154).

**Comment by deuill** [comment]
Closing this as already implemented, please open a new issue if there's some missing functionality here.
