### ISSUE TITLE
Compile Error On Mac OS Catalina

### ISSUE THREAD

**Issue by devsimsek** [deuill/go-php#69]
I am trying to go get but it generates error.
Error;
```
 go get -u -v -tags 'php7 darwin' github.com/deuill/go-php
github.com/deuill/go-php
# github.com/deuill/go-php
../../../../../pkg/mod/github.com/deuill/go-php@v0.0.0-20181001205857-9d111e73423d/context.go:11:11: fatal error: 'main/php.h' file not found
 #include <main/php.h>
          ^~~~~~~~~~~~
1 error generated.

```
I don't know how to fix it. please reply fast.

**Comment by ghost** [comment]
# github.com/deuill/go-php
../../pkg/mod/github.com/deuill/go-php@v0.0.0-20181001205857-9d111e73423d/context.go:11:23: fatal error: main/php.h: No such file or directory
 // #include <main/php.h>
