### ISSUE TITLE
PHP 7.0 has Released, we need Support PHP 7.0

### ISSUE THREAD

**Issue by xulei8** [deuill/go-php#8]
Hello
PHP 7.0 has released .  All us know that PHP 7.0 is much more  modern than other version . So I think that we need sopport php 7.0 . I've tried to do this , bus php 7.0 have many changes in data pointor.

We need not to support other php versions so on .
And it's difficult to compile php libs so we need to download the php libs in github .And we need to upload  the php head files in the project so that we'll never download the php source file . 

thanks .

**Comment by deuill** [comment]
PHP 7 compatibility is most definitely something that needs working on, however it may be some time until we can advertise full support, seeing as there's a lot of work to be done on 5.6 as it is...

It also may be some time until PHP 7 sees widespread support, so it's not a critical priority for me at the moment. You are more than welcome to contribute, however!

**Comment by deuill** [comment]
Pull request #12 tracks this issue.

**Comment by deuill** [comment]
Closed by #12
